// Folder List
export const FOLDER_LIST_REQUEST = 'FOLDER_LIST_REQUEST';
export const FOLDER_LIST_SUCCESS = 'FOLDER_LIST_SUCCESS';
export const FOLDER_LIST_FAIL = 'FOLDER_LIST_FAIL';

// Folder Details
export const FOLDER_DETAILS_REQUEST = 'FOLDER_DETAILS_REQUEST';
export const FOLDER_DETAILS_SUCCESS = 'FOLDER_DETAILS_SUCCESS';
export const FOLDER_DETAILS_FAIL = 'FOLDER_DETAILS_FAIL';
