// Single Image
export const IMAGE_DETAILS_REQUEST = 'IMAGE_DETAILS_REQUEST';
export const IMAGE_DETAILS_SUCCESS = 'IMAGE_DETAILS_SUCCESS';
export const IMAGE_DETAILS_FAIL = 'IMAGE_DETAILS_FAIL';

// Single Datasheet
export const DATASHEET_DETAILS_REQUEST = 'DATASHEET_DETAILS_REQUEST';
export const DATASHEET_DETAILS_SUCCESS = 'DATASHEET_DETAILS_SUCCESS';
export const DATASHEET_DETAILS_FAIL = 'DATASHEET_DETAILS_FAIL';

// Single Drawing
export const DRAWING_DETAILS_REQUEST = 'DRAWING_DETAILS_REQUEST';
export const DRAWING_DETAILS_SUCCESS = 'DRAWING_DETAILS_SUCCESS';
export const DRAWING_DETAILS_FAIL = 'DRAWING_DETAILS_FAIL';

// Single Manual
export const MANUAL_DETAILS_REQUEST = 'MANUAL_DETAILS_REQUEST';
export const MANUAL_DETAILS_SUCCESS = 'MANUAL_DETAILS_SUCCESS';
export const MANUAL_DETAILS_FAIL = 'MANUAL_DETAILS_FAIL';
