// Page List
export const NOTICIA_LIST_REQUEST = 'NOTICIA_LIST_REQUEST';
export const NOTICIA_LIST_SUCCESS = 'NOTICIA_LIST_SUCCESS';
export const NOTICIA_LIST_FAIL = 'NOTICIA_LIST_FAIL';

// Page Details
export const NOTICIA_DETAILS_REQUEST = 'NOTICIA_DETAILS_REQUEST';
export const NOTICIA_DETAILS_SUCCESS = 'NOTICIA_DETAILS_SUCCESS';
export const NOTICIA_DETAILS_FAIL = 'NOTICIA_DETAILS_FAIL';
