// Page List
export const PAGE_LIST_REQUEST = 'PAGE_LIST_REQUEST';
export const PAGE_LIST_SUCCESS = 'PAGE_LIST_SUCCESS';
export const PAGE_LIST_FAIL = 'PAGE_LIST_FAIL';

// Page Details
export const PAGE_DETAILS_REQUEST = 'PAGE_DETAILS_REQUEST';
export const PAGE_DETAILS_SUCCESS = 'PAGE_DETAILS_SUCCESS';
export const PAGE_DETAILS_FAIL = 'PAGE_DETAILS_FAIL';
