// Products
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

// Products
export const FILTEREDPROD_LIST_REQUEST = 'FILTEREDPROD_LIST_REQUEST';
export const FILTEREDPROD_LIST_SUCCESS = 'FILTEREDPROD_LIST_SUCCESS';
export const FILTEREDPROD_LIST_FAIL = 'FILTEREDPROD_LIST_FAIL';

// Single Product
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
