// Series List
export const SERIE_LIST_REQUEST = 'SERIE_LIST_REQUEST';
export const SERIE_LIST_SUCCESS = 'SERIE_LIST_SUCCESS';
export const SERIE_LIST_FAIL = 'SERIE_LIST_FAIL';

// Serie Details
export const SERIE_DETAILS_REQUEST = 'SERIE_DETAILS_REQUEST';
export const SERIE_DETAILS_SUCCESS = 'SERIE_DETAILS_SUCCESS';
export const SERIE_DETAILS_FAIL = 'SERIE_DETAILS_FAIL';
